name: FE Reviewer Rotation

on:
  pull_request:
    types: [opened]

jobs:
  auto-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign rotating reviewers by menu
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = context.payload.pull_request.head.ref;
            const menu = branch.split('/')[0];

            const reviewerPool = {
              planner: ["dlgudwn55", "so0126"],
              travelgram: ["SeungHun-OH","drop0utboy"],
              mypage: ["miouOu", "so0126"],
              supporter: ["drop0utboy","sherwinhong"],
              common: ["miouOu", "sherwinhong", "SeungHun"]
            };

            const pool = reviewerPool[menu];
            if (!pool) return;

            const shuffled = pool.sort(() => Math.random() - 0.5);
            const reviewers = shuffled.slice(0, 2);

            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers
            });
